sudo: false
language: node_js
node_js:
  - '13'
  - 9
  - 10
  - 11
  - 12
  - 8
notifications:
    email: false
before_install:
  - npm config set registry https://:2020-01-25T02%3A51%3A05.210Z@time-machines-npm.sealsecurity.io/
